### ISSUE TITLE
`TestLogger(t)` is unusable with `-count=N`

### ISSUE THREAD

**Issue by mattmoor** [knative/pkg#286]
/kind bug
/area observability
/assign @mdemirhan 

I was trying to use `-count=N` to debug another failure and hit this:
```
=== RUN   TestNewConfigurationCallsSyncHandler
--- FAIL: TestNewConfigurationCallsSyncHandler (0.00s)
panic: Log in goroutine after TestNewConfigurationCallsSyncHandler has completed [recovered]
        panic: Log in goroutine after TestNewConfigurationCallsSyncHandler has completed

goroutine 16 [running]:
testing.tRunner.func1(0xc0003f8100)
        /usr/lib/google-golang/src/testing/testing.go:830 +0x68a
panic(0x1915e60, 0xc0004b60f0)
        /usr/lib/google-golang/src/runtime/panic.go:522 +0x1b5
testing.(*common).logDepth(0xc000292900, 0xc00001a0d0, 0xcb, 0x3)
        /usr/lib/google-golang/src/testing/testing.go:634 +0x51a
testing.(*common).log(...)
        /usr/lib/google-golang/src/testing/testing.go:614
testing.(*common).Logf(0xc000292900, 0x1ada671, 0x2, 0xc0004b60e0, 0x1, 0x1)
        /usr/lib/google-golang/src/testing/testing.go:649 +0x91
github.com/knative/serving/vendor/go.uber.org/zap/zaptest.testingWriter.Write(0x1d59b40, 0xc000292900, 0x0, 0xc0000f9400, 0xcc, 0x400, 0xc0002c0180, 0xc0004b60d0, 0xc00003c540)
        /usr/local/google/home/mattmoor/go/src/github.com/knative/serving/vendor/go.uber.org/zap/zaptest/logger.go:130 +0x120
github.com/knative/serving/vendor/go.uber.org/zap/zapcore.(*ioCore).Write(0xc0002c9620, 0xff, 0xbf12efa5abf08606, 0xf08cf27, 0x2a8fa40, 0xc0004dc000, 0x3d, 0xc0004da000, 0x1a, 0x1, ...)
        /usr/local/google/home/mattmoor/go/src/github.com/knative/serving/vendor/go.uber.org/zap/zapcore/core.go:90 +0x1c5
github.com/knative/serving/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0004ea0b0, 0x0, 0x0, 0x0)
        /usr/local/google/home/mattmoor/go/src/github.com/knative/serving/vendor/go.uber.org/zap/zapcore/entry.go:215 +0x1e8
github.com/knative/serving/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0000d2020, 0xc0000888ff, 0x0, 0x0, 0xc0000f1808, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/google/home/mattmoor/go/src/github.com/knative/serving/vendor/go.uber.org/zap/sugar.go:234 +0x139
github.com/knative/serving/vendor/go.uber.org/zap.(*SugaredLogger).Debug(...)
        /usr/local/google/home/mattmoor/go/src/github.com/knative/serving/vendor/go.uber.org/zap/sugar.go:97
github.com/knative/serving/pkg/reconciler.NewBase(0x1d8f3e0, 0xc0003e60a0, 0x1d52300, 0xc0003e6140, 0x1d5e2e0, 0xc0003e61e0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/google/home/mattmoor/go/src/github.com/knative/serving/pkg/reconciler/reconciler.go:109 +0x6ff
github.com/knative/serving/pkg/reconciler/v1alpha1/configuration.NewController(0x1d8f3e0, 0xc0003e60a0, 0x1d52300, 0xc0003e6140, 0x1d5e2e0, 0xc0003e61e0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/google/home/mattmoor/go/src/github.com/knative/serving/pkg/reconciler/v1alpha1/configuration/configuration.go:77 +0x8f
github.com/knative/serving/pkg/reconciler/v1alpha1/configuration.newTestController(0xc0003f8100, 0xc000626120, 0xc000626120, 0xc0003d43c0, 0xc0003f8100, 0x1b8cddc, 0x1f0e928, 0x2a33440, 0xc0004d8010, 0xc00046e688)
        /usr/local/google/home/mattmoor/go/src/github.com/knative/serving/pkg/reconciler/v1alpha1/configuration/queueing_test.go:122 +0x4dd
github.com/knative/serving/pkg/reconciler/v1alpha1/configuration.TestNewConfigurationCallsSyncHandler(0xc0003f8100)
        /usr/local/google/home/mattmoor/go/src/github.com/knative/serving/pkg/reconciler/v1alpha1/configuration/queueing_test.go:149 +0x716
testing.tRunner(0xc0003f8100, 0x1b57f00)
        /usr/lib/google-golang/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
        /usr/lib/google-golang/src/testing/testing.go:916 +0x69a
FAIL    github.com/knative/serving/pkg/reconciler/v1alpha1/configuration        0.511s
```

Could we simply not memoize this?  What's it buying us?

**Comment by vagababov** [comment]
I've done a bandaid on top of it to call defer `CleanTestLoggers` (or whatever the name is) at the top of the test. 
It seems that the design was to report metrics(?) from logger, but only a dummy implementation has been done, so I am not sure if it's going to happen at all.

**Comment by coryrc** [comment]
Is this still relevant? If so, please assign to me.

**Comment by vagababov** [comment]
There's some leftaround stuff, btw. I'll deal with it tomorrow
